services:
  - type: web
    name: lista-de-tarefas-laravel
    env: php
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: php artisan migrate --force && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://todo-list-laravel.onrender.com
